list_of_supported_langs_google = ['af', 'ak', 'am', 'ar', 'as', 'ay', 'az', 'be', 'bg', 'bho', 'bm', 'bn', 'bs', 'ca', 'ceb', 'ckb', 'co', 'cs', 'cy', 'da', 'de','doi','dv','ee', 'el', 'en', 'en-US', 'eo', 'es', 'et', 'eu', 'fa', 'fi', 'fr', 'fy', 'ga', 'gd', 'gl', 'gn', 'gom', 'gu', 'ha', 'haw', 'hi','hmn','hr','ht', 'hu', 'hy', 'id', 'ig', 'ilo', 'is', 'it', 'iw', 'ja', 'jw', 'ka', 'kk', 'km','kn', 'ko', 'kri', 'ku', 'ky', 'la', 'lb', 'lg', 'ln', 'lo', 'lt', 'lus', 'lv', 'mai', 'mg', 'mi', 'mk', 'ml', 'mn', 'mni-Mtei', 'mr', 'ms', 'mt', 'my', 'ne', 'nl', 'no', 'nso', 'ny', 'om', 'or', 'pa', 'pl', 'ps', 'pt', 'qu', 'ro', 'ru', 'rw', 'sa', 'sd', 'si', 'sk', 'sl', 'sm', 'sn', 'so', 'sq', 'sr', 'st', 'su', 'sv', 'sw', 'ta', 'te', 'tg', 'th', 'ti', 'tk', 'tl', 'tr', 'ts', 'tt', 'ug', 'uk', 'ur', 'uz', 'vi', 'xh', 'yi', 'yo','zh-CN', 'zh-TW', 'zu']
list_of_supported_langs_bing = ['af', 'am', 'ar', 'as', 'az', 'ba', 'bg', 'bn', 'bo', 'bs', 'ca', 'cs', 'cy', 'da', 'de', 'dv', 'el', 'en', 'es', 'et', 'eu', 'fa', 'fi', 'fil', 'fj', 'fo', 'fr', 'fr-CA', 'ga','gl', 'gu', 'he', 'hi', 'hr', 'hsb', 'ht', 'hu', 'hy', 'id', 'ikt', 'is', 'it', 'iu', 'iu-Latn', 'ja', 'ka','kk', 'km', 'kmr', 'kn', 'ko', 'ku', 'ky', 'lo', 'lt', 'lv', 'lzh', 'mg', 'mi', 'mk', 'ml', 'mn-Cyrl', 'mn-Mong', 'mr', 'ms', 'mt', 'mww', 'my', 'nb', 'ne', 'nl', 'or', 'otq', 'pa', 'pl', 'prs', 'ps', 'pt', 'pt-PT', 'ro', 'ru', 'sk', 'sl', 'sm', 'so', 'sq', 'sr-Cyrl', 'sr-Latn', 'sv', 'sw', 'ta', 'te', 'th', 'ti', 'tk', 'tlh-Latn', 'to', 'tr', 'tt', 'ty', 'ug', 'uk', 'ur', 'uz', 'vi', 'yua', 'yue', 'zh-Hans', 'zh-Hant', 'zu']
list_of_supported_langs_deepl = ['bg', 'cs', 'da', 'de', 'el', 'en', 'es', 'et', 'fi', 'fr', 'hu', 'id', 't', 'ja', 'lt', 'lv', 'nl', 'pl', 'pt', 'ro', 'ru', 'sk', 'sl', 'sv', 'tr', 'zh']
list_of_supported_langs_itranslate = ['af', 'ar-AE', 'ar-EG', 'ar-SA', 'az', 'be', 'bg', 'bn','bs', 'ca', 'ceb', 'cs', 'cy', 'da', 'de', 'el', 'en-AU', 'en-UK', 'en-US', 'eo', 'es-ES', 'es-MX', 'es-US','et', 'eu', 'fa', 'fi', 'fr-CA', 'fr-FR', 'ga', 'gl', 'gu', 'ha', 'he', 'hi', 'hmn', 'hr', 'ht', 'hu', 'hy','id', 'ig', 'is', 'it', 'ja', 'jw', 'ka', 'kk', 'km', 'kn', 'ko', 'la', 'lo', 'lt', 'lv', 'mg', 'mi', 'mk', 'ml', 'mn', 'mr', 'ms', 'mt', 'my', 'ne', 'nl', 'no', 'ny', 'pa', 'pl', 'pt-BR', 'pt-PT', 'ro', 'ru', 'si', 'sk', 'sl', 'so', 'sq', 'sr', 'st', 'su', 'sv', 'sw', 'ta', 'te', 'tg', 'th', 'tl', 'tr', 'uk', 'ur', 'uz', 'vi', 'yi', 'yo', 'zh-CN', 'zh-HK', 'zh-TW', 'zu']
list_of_supported_langs_reverso = ['af', 'ar', 'bg', 'bn', 'cs', 'da', 'de', 'el', 'en', 'es', 'et', 'fa', 'fi', 'fr', 'ha', 'he', 'hi', 'hu', 'id', 'it', 'ja', 'ko', 'lt', 'nl', 'no', 'pe', 'pl', 'ps', 'pt', 'ro', 'ru', 'sk', 'sl', 'so', 'sr', 'sv', 'th', 'tr', 'uk', 'ur', 'vi', 'zh']


list_of_supported_langs_google = ", ".join(map(str, list_of_supported_langs_google))
list_of_supported_langs_bing = ", ".join(map(str, list_of_supported_langs_bing))
list_of_supported_langs_deepl = ", ".join(map(str, list_of_supported_langs_deepl))
list_of_supported_langs_itranslate = ", ".join(map(str, list_of_supported_langs_itranslate))
list_of_supported_langs_reverso = ", ".join(map(str, list_of_supported_langs_reverso))
